defaults:
  - defaults
  - override hydra/sweeper: optuna
  - _self_


hydra:
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: gnn
    storage: null
    n_trials: 20
    n_jobs: 1
    # max_failure_rate: 0.0
    params:
      lr: tag(log, interval(1e-4, 1e-2))
      num_layers: choice(1, 2, 3)

